model_method : hdbscan
ground_percentage : 0.6
self.use_estimated_dist : True


objects:  
  person:
    eps : 0.2
    contract_percentage_bottom : 10
    contract_percentage_top : 10
    contract_percentage_sides : 10 
    max_depth : 0.2
    unique : x

  bicycle:
    eps : 0.5
    contract_percentage_bottom : 10
    contract_percentage_top : 10
    contract_percentage_sides : 10 
    max_depth : 0.2
    unique : y

  car:
    eps : 0.2
    contract_percentage_bottom : 10
    contract_percentage_top : 10
    contract_percentage_sides : 15 
    max_depth : 0.15  
    unique : xy

  clock:
    eps : 0.2
    contract_percentage_bottom : 0
    contract_percentage_top : 0
    contract_percentage_sides : 0 
    max_depth : 0.3
    unique : xy

  bottle:
    eps : 0.2
    contract_percentage_bottom : 0
    contract_percentage_top : 0
    contract_percentage_sides : 0 
    max_depth : 0.3
    unique : xy

  umbrella:
    eps : 0.2
    contract_percentage_bottom : 5
    contract_percentage_top : 5
    contract_percentage_sides : 5 
    max_depth : 0.4
    unique : xy