R_camera_lidar :
  - [-1.0, 0.0, 0.0]
  - [ 0.0, 0.0,-1.0]
  - [ 0.0,-1.0, 0.0]

R_correction   :
  - [1.0, 0.0, 0.0]
  - [0.0, 1.0, 0.0]
  - [0.0, 0.0, 1.0]
  
t_camera_lidar : [-0.045, -0.293, -0.241]